apiVersion: v1
kind: Service
metadata:
    name: "assistantreg-272f"
    labels:
        app: "assistantreg-272f"
spec:
    type: LoadBalancer
    ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: http
    selector:
        app: "assistantreg-272f"